env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  no-console: off
  no-param-reassign: off
  max-len:
    - error 
    - code: 100
      ignoreComments: true
      ignoreTemplateLiterals: true
      ignoreStrings: true
  no-return-assign: 
    - error
    - except-parens
  arrow-parens:
    - 2
    - as-needed
    - requireForBlockBody: true
